# Generated by Django 5.1.15 on 2026-04-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "minimum_lease_term_months",
                    models.PositiveIntegerField(
                        default=12, help_text="Minimum lease duration in months"
                    ),
                ),
                (
                    "require_screening_for_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Require completed screening before lease can be approved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=20)),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("owner_occupied", "Owner Occupied"),
                            ("rented", "Rented"),
                            ("vacant", "Vacant"),
                        ],
                        default="owner_occupied",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hoa_property",
                    models.ForeignKey(
                        db_column="property_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_number"],
                "unique_together": {("hoa_property", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="UnitOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("acquired_date", models.DateField()),
                ("disposed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "is_current"],
                        name="properties__owner_i_ff56b9_idx",
                    ),
                    models.Index(
                        fields=["unit", "is_current"],
                        name="properties__unit_id_064cac_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("unit",),
                        name="unique_current_owner_per_unit",
                    )
                ],
            },
        ),
    ]
