# Generated by Django 5.1.15 on 2026-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningrecord",
            name="attestation_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="attestation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="owner_attested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="owner_attested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
