# Generated by Django 5.1.15 on 2026-04-12 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="lease",
            name="leases_leas_unit_id_d203d6_idx",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="tenant_email",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="tenant_first_name",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="tenant_last_name",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="tenant_phone",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="unit",
        ),
        migrations.AddField(
            model_name="lease",
            name="unit_number",
            field=models.CharField(
                default="", help_text="Unit number (e.g., 101, 2A)", max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["unit_number", "status"], name="leases_leas_unit_nu_282802_idx"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="leases.lease",
            ),
        ),
    ]
