# Generated by Django 5.1.15 on 2026-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
